# Generated by Django 4.2.7 on 2024-04-08 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='borrowed_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
