# Generated by Django 4.2.7 on 2024-02-22 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
