# Generated by Django 4.2.7 on 2023-12-16 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemprofiling',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
