# Generated by Django 4.2.7 on 2024-02-22 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventory_is_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='reserved_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='itemcopy',
            name='is_reserved',
            field=models.BooleanField(default=False),
        ),
    ]
