# Generated by Django 4.2.7 on 2023-12-02 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_rename_quantity_inventory_total_quantity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='total_quantity',
            new_name='quantity',
        ),
    ]
