# Generated by Django 4.2.7 on 2023-12-29 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_itemcopy_previous_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcopy',
            name='previous_status',
        ),
    ]
