# Generated by Django 4.2.7 on 2023-12-29 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_itemcopy_previous_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcopy',
            name='previous_status',
            field=models.CharField(choices=[('Acceptable', 'Acceptable'), ('Good', 'Good'), ('Like new', 'Like new'), ('Damaged', 'Damaged'), ('Lost', 'Lost')], default='Good', max_length=50),
        ),
    ]
