# Generated by Django 4.2.7 on 2023-12-29 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_itemcopy_previous_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcopy',
            name='previous_status',
        ),
        migrations.AddField(
            model_name='itemcopy',
            name='previous_is_borrowed',
            field=models.BooleanField(default=False),
        ),
    ]
