# Generated by Django 4.2.7 on 2024-02-15 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_remove_itemcopy_previous_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemprofiling',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
    ]
