# Generated by Django 4.2.7 on 2023-12-04 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='date_preferred',
            field=models.DateField(),
        ),
    ]
