# Generated by Django 4.2.7 on 2024-03-09 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_initial'),
        ('transactions', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='posts.post'),
        ),
    ]
