# Generated by Django 4.2.7 on 2023-12-15 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactionitem',
            old_name='inventory_item',
            new_name='inventory',
        ),
        migrations.RenameField(
            model_name='transactionitem',
            old_name='item_copy',
            new_name='item',
        ),
    ]
