# Generated by Django 4.2.7 on 2024-04-09 16:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='status_updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
