# Generated by Django 4.2.7 on 2024-05-08 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionitem',
            name='condition',
            field=models.CharField(blank=True, choices=[('Good', 'Good'), ('Slightly Damaged', 'Slightly Damaged'), ('Damaged', 'Damaged'), ('Broken', 'Broken'), ('Lost', 'Lost')], max_length=50, null=True),
        ),
    ]
