# Generated by Django 4.2.7 on 2023-12-15 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_rename_inventory_item_transactionitem_inventory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='remarks',
            field=models.TextField(default='empty'),
        ),
    ]
