# Generated by Django 4.2.7 on 2024-05-14 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_transaction_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='org_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
