# Generated by Django 4.2.7 on 2024-04-10 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_inquiry_status_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
