# Generated by Django 4.2.7 on 2024-05-14 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_transaction_org_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('Release', 'Release'), ('Donation', 'Donation'), ('Maintenance', 'Maintenance')], max_length=20),
        ),
    ]
