# Generated by Django 4.2.7 on 2023-12-05 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('transactions', '0004_alter_transaction_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionitem',
            name='item_copy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_items_itemcopy', to='inventory.itemcopy'),
        ),
        migrations.AddField(
            model_name='transactionitem',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactionitem',
            name='inventory_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_items_inventory', to='inventory.inventory'),
        ),
        migrations.CreateModel(
            name='ReservedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('Inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserved_items', to='transactions.inquiry')),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ReserveItem', to='inventory.inventory')),
            ],
        ),
    ]
