# Generated by Django 4.2.7 on 2023-12-15 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_transaction_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
