# Generated by Django 4.2.7 on 2023-12-16 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_itemprofiling_description'),
        ('transactions', '0005_alter_transaction_remarks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserveditem',
            old_name='item_copy',
            new_name='item',
        ),
        migrations.RemoveField(
            model_name='reserveditem',
            name='inventory_item',
        ),
        migrations.AddField(
            model_name='reserveditem',
            name='inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reserved_items', to='inventory.inventory'),
        ),
    ]
