# Generated by Django 4.2.7 on 2024-05-22 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='date_preferred',
            field=models.DateTimeField(),
        ),
    ]
