# Generated by Django 4.2.7 on 2023-12-05 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('transactions', '0005_transactionitem_item_copy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserveditem',
            name='item_copy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ReserveItem_itemcopy', to='inventory.itemcopy'),
        ),
    ]
