# Generated by Django 4.2.7 on 2023-12-18 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_transaction_inquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionitem',
            name='status',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Returned', 'Returned')], max_length=10, null=True),
        ),
    ]
