# Generated by Django 4.2.7 on 2023-12-28 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_transactionitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionitem',
            name='status',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Returned', 'Returned'), ('Lost', 'Lost'), ('Consumable', 'Consumable')], max_length=10, null=True),
        ),
    ]
