# Generated by Django 4.2.7 on 2023-12-29 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0010_alter_transactionitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionitem',
            name='condition',
            field=models.CharField(blank=True, choices=[('Acceptable', 'Acceptable'), ('Good', 'Good'), ('Like new', 'Like new'), ('Damaged', 'Damaged'), ('Lost', 'Lost')], max_length=50, null=True),
        ),
    ]
