# Generated by Django 4.2.7 on 2023-12-01 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_contact_alter_user_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('position', models.CharField(choices=[('Program Officer', 'Program Officer'), ('Director', 'Director')], max_length=255)),
                ('date_hired', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Staff Members',
            },
        ),
    ]
