# Generated by Django 4.2.7 on 2023-12-02 06:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='date_hired',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
