# Generated by Django 4.2.7 on 2023-12-02 06:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_staff_date_hired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='date_hired',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
